[package]
name = "difflib-rs"
version = "0.1.1"
edition = "2021"

[lib]
name = "difflib_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module", "abi3-py310"] }
rustc-hash = "2.0"