[package]
name = "difflib-rst"
version = "0.1.0"
edition = "2021"

[lib]
name = "difflib_rst"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
rustc-hash = "2.0"